gitops-runtime:
  global:
    codefresh:
      accountId: 61289cb0432d871402610bad
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: pasha-monorepo
  argo-cd: 
    server:
      image:
        imagePullPolicy: Always
      service:
        type: LoadBalancer   
    acrController:
       enabled: true
       image: 
         tag: v2.12-2024.9.30-a87492b22
