gitops-runtime:
  global:
    codefresh:
      accountId: 61289cb0432d871402610bad
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: pasha-personal-v2
