apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: alina
spec:
  destination:
    namespace: default
    server: https://B2A8F47D84174C53308248C7BB3693A1.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/codefresh-hosted/*.yaml,runtimes/codefresh-hosted/**/*.yaml,codefresh-hosted-managed-cluster-alina-cm.yaml}
      recurse: true
    path: resources
    repoURL: >-
      https://github.com/oleksandr-codefresh/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
