apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-gitops-runtime
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/oleksandr-codefresh/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
    path: resources/pasha-personal-v7/chart
    helm:
      releaseName: cf-gitops-runtime
  destination:
    namespace: cf-v2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
