apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: scale-prod
spec:
  destination:
    namespace: default
    server: https://403E08D8DDCCFB612E8E5EB57670660E.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/codefresh/*.yaml,runtimes/codefresh/**/*.yaml,codefresh-managed-cluster-scale-prod-cm.yaml}
      recurse: true
    path: resources
    repoURL: >-
      https://github.com/oleksandr-codefresh/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
