gitops-runtime:
  # event-reporters:
  #   events:
  #     argoCDServerServiceName: "5.tcp.eu.ngrok.io"
  #     argoCDServerServicePort: "16277"
  # argo-events:
  #   global:
  #     image:
  #       tag: v1.8.0-cap-CR-19893
  argo-rollouts:
    controller:
      replicas: 0
  argo-cd:
    repoServer:
      replicas: 2
      resources:
        requests:
          cpu: "1"
          memory: "200Mi"

    controller:
      replicas: 1
      resources:
        requests:
          cpu: "3"
          memory: "8Gi"
      image:
        tag: v2.8.1-cap-CR-create-apps-with-err
    server:
      replicas: 3
      service:
        type: LoadBalancer
      resources:
        requests:
          cpu: "0.3"
          memory: "400Mi"
    eventReporter:
      enabled: true
      version: v2
      replicas: 10
      image:
        tag: v2.9-2024.01.17-0d221227f
      metrics:
        enabled: true
      env:
      - name: ARGOCD_SERVER_ROOTPATH
        valueFrom:
          configMapKeyRef:
            name: argocd-cmd-params-cm
            key: server.rootpath
            optional: true
      #   - name: "USE_GRPC"
      #     value: "false"
      resources:
        requests:
          cpu: "0.2"
          memory: "200Mi"
    configs:
      cm:
        timeout.reconciliation: 180s
#        resource.ignoreResourceUpdatesEnabled: true
        resource.customizations.ignoreDifferences.Service: |
          jsonPointers:
          - /spec/sessionAffinity
          - /status
#        resource.compareoptions: |
#          ignoreDifferencesOnResourceUpdates: true
      params:
        controller.status.processors: "70"
        controller.operation.processors: "50"
        controller.log.level: "debug"
        # controller.self.heal.timeout.seconds: 360

  global:
    codefresh:
      accountId: 61289cb0432d871402610bad
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
