gitops-runtime:
  argo-events:
    global:
      image:
        tag: v1.8.0-cap-CR-19893
  global:
    codefresh:
      accountId: 61289cb0432d871402610bad
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: argo-load
