gitops-runtime:
  event-reporters:
    events:
      argoCDServerServiceName: "5.tcp.eu.ngrok.io"
      argoCDServerServicePort: "16277"
  argo-events:
    global:
      image:
        tag: v1.8.0-cap-CR-19893
  argo-cd:
    repoServer:
      replicas: 0
    controller:
      replicas: 0
      resources:
        requests:
          cpu: "3"
          memory: "4Gi"
    server:
      replicas: 0
      image:
        repository: docker.io/xeonalex/personal-argocd-dev
        tag: 2.8.1-parrallel-events-13
      service:
        type: LoadBalancer
  global:
    codefresh:
      accountId: 61289cb0432d871402610bad
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: argo-load
