gitops-runtime:
  # event-reporters:
  #   events:
  #     argoCDServerServiceName: "5.tcp.eu.ngrok.io"
  #     argoCDServerServicePort: "16277"
  # argo-events:
  #   global:
  #     image:
  #       tag: v1.8.0-cap-CR-19893
  argo-cd:
    repoServer:
      replicas: 1
      resources:
        requests:
          cpu: "2"
          memory: "2Gi"

    controller:
      replicas: 2
      resources:
        requests:
          cpu: "3"
          memory: "4Gi"
    server:
      replicas: 3
      service:
        type: LoadBalancer
    eventReporter:
      enabled: true
      version: v2
      replicas: 5
      metrics:
        enabled: true
    configs:
      params:
        controller.status.processors: "25"
        controller.operation.processors: "15"
  global:
    codefresh:
      accountId: 61289cb0432d871402610bad
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: argo-load
