gitops-runtime:
  # event-reporters:
  #   events:
  #     argoCDServerServiceName: "5.tcp.eu.ngrok.io"
  #     argoCDServerServicePort: "16277"
  argo-events:
    global:
      image:
        tag: v1.8.0-cap-CR-19893
  argo-cd:
    server:
      service:
        type: LoadBalancer
  global:
    codefresh:
      accountId: 61289cb0432d871402610bad
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: argo-load
