apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-version
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrii-codefresh/local52-gs.git
    path: load
    targetRevision: main
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: codefresh
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
