apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monorepo-gs
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pasha-codefresh/scale-test.git
    path: monorepo-apps
    targetRevision: main
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: codefresh
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
     allowEmpty: true
     prune: true
     selfHeal: true
